import collections.abc
import csv
import json
import logging
from datetime import datetime
from typing import TextIO

import numpy as np
import scipy.optimize
import scipy.signal
import uncertainties
import uncertainties.umath as umath
from findpeaks import findpeaks
from uncertainties import ufloat

# squelch findpeaks logger messages
logging.getLogger('findpeaks').setLevel(logging.CRITICAL + 1)

# April 17th data
# Cesium 137:
#   120 seconds live time,
#   661.657 keV: 96532 counts, 804.43 counts/second
# Cobalt 60:
#   120 seconds live time,
#   1173.228 keV, 23310 counts, 194.25 counts/second
#   1332.492 keV, 16566 counts, 138.05 counts/second
# Europium 152:
#   120 seconds live time,
#   121.7817 keV, 98512 counts, 820.93 counts/second
# Unknown:
#   120 seconds live time,
#   78.54 keV, 493.87±2.72 counts/second
#   302.56 keV, 65.85±1.66 counts/second
#   361.11 keV, 477.31±2.8 counts/second
#   516.87 keV, 65.52±1.09 count/second
#   1259.55 keV, 19.22±0.56 counts/second
#   115?.16 keV, 32.02±1.21 counts/second (unsure)

# 3% voltage accuracy per the manual
detector_voltage = (ufloat(900, 0.03 * 900),)
# 5% live time correction accuracy per the manual
# TODO not sure if this is the correct formula for 5% accuracy
live_time = ufloat(120, 0.05 * 120)
fine_gain = 1.0
coarse_gain = 2.0


def parse_prospect_csv(file: TextIO):
    """Get the data from the ProSpect CSV file.

    Args:
        file:
            The pulse height analysis CSV file generated by ProSpect.

    Returns:
        The start time, real time, live time, and spectrum data dictionary in
        that order. The dictionary has the following keys: 'channels', 'energies',
        'counts'.
    """
    # consume the header lines before invoking the csv reader
    header = []
    for line in file:
        if line.startswith("Spectrum"):
            break
        header.append(line.strip("\r\n"))

    # Fri Apr 10 12:04:11 GMT-0400 2026
    start_time = datetime.strptime(
        header[0].split(", ")[-1], "%a %b %d %H:%M:%S %Z%z %Y"
    )
    # two spaces after comma
    energy_calibration = []
    for i, coef in enumerate(header[1].split(",  ")[-1].split(", ")):
        energy_calibration.append(coef.split(", ")[-1])
    energy_calibration = tuple(energy_calibration)
    live_time = float(header[2].split(", ")[-1])
    real_time = float(header[3].split(", ")[-1])

    # 5% accuracy on live time correction per the datasheet
    live_time = ufloat(live_time, 0.05 * live_time)

    # at this point, spectrum file object is seeked to the header line
    # "Channel, Energy (keV), Counts"
    reader = csv.DictReader(file, skipinitialspace=True)
    spectrum_data = {"channels": [], "energies": [], "counts": []}
    for rowdict in reader:
        spectrum_data["channels"].append(int(rowdict["Channel"]))
        spectrum_data["energies"].append(float(rowdict["Energy (keV)"]))
        spectrum_data["counts"].append(int(rowdict["Counts"]))
    # convert to arrays after, to take advantage of python's list type
    # being linked for quick appending. using numpy.append would do a
    # copy operation for each line in the csv file.
    spectrum_data["channels"] = np.array(spectrum_data["channels"])  # ty: ignore[invalid-assignment]
    spectrum_data["energies"] = np.array(spectrum_data["energies"])  # ty: ignore[invalid-assignment]
    spectrum_data["counts"] = np.array(spectrum_data["counts"])  # ty: ignore[invalid-assignment]
#    spectrum_data["channels"] = spectrum_data["channels"]  # ty: ignore[invalid-assignment]
#    spectrum_data["energies"] = spectrum_data["energies"]  # ty: ignore[invalid-assignment]
#    spectrum_data["counts"] = spectrum_data["counts"]  # ty: ignore[invalid-assignment]

    return start_time, real_time, live_time, spectrum_data


def scrub_uncertainties(x):
    if isinstance(x, collections.abc.Sequence):
        scrubbed = []
        for i in x:
            if isinstance(i, uncertainties.UFloat):
                scrubbed.append(i.nominal_value)
            else:
                scrubbed.append(i)
        return scrubbed
    elif isinstance(x, uncertainties.core.UFloat):
        return x.nominal_value
    else:
        return x


def get_uncertainties(x):
    if isinstance(x, collections.abc.Sequence):
        scrubbed = []
        for i in x:
            if isinstance(i, uncertainties.UFloat):
                scrubbed.append(i.std_dev)
            else:
                scrubbed.append(0)
        return scrubbed
    elif isinstance(x, uncertainties.core.UFloat):
        return x.std_dev
    else:
        return 0


check_source_properties = {
    "137Cs": {
        # in years
        "half_life": ufloat(30.007, 0.00046),
        # we assume time uncertainty is neglibile, since these sources have been decaying for years
        "assay_date": datetime(1995, 10, 13),
        "calibration_date": datetime(2026, 4, 17),
        # microCurie to Becquerel
        "initial_activity": ufloat(1.0, 0.2 * 1.0) * 1e-6 * 3.7e10,
        # some energies have no listed uncertainty on www.nndc.bnl.gov/nudat3
        # all energies are in keV
        "energies": (ufloat(661.657, 0.0003),),
        "intensities": (ufloat(0.8510, 0.00020),),
        # as reported by ProSpect. raw values, not subtracted from noise floor
        "peak_counts": (96532,),
        # forgot to record uncertainty
        "peak_counts_per_second": (804.43,),
    },
    "152Eu": {
        "half_life": ufloat(13.517, 0.0009),
        "assay_date": datetime(2013, 1, 3),
        "calibration_date": datetime(2026, 4, 17),
        # TODO uncertainty is 20% or 5%?
        "initial_activity": ufloat(1.02, 0.20) * 1e-6 * 3.7e10,
        "energies": (ufloat(121.7817, 0.00003),),
        "intensities": (ufloat(0.2853, 0.000016),),
        "peak_counts": (98512,),
        "peak_counts_per_second": (820.93,),
    },
    "60Co": {
        "half_life": ufloat(5.271, 0.0002),
        "assay_date": datetime(2013, 1, 1),
        "calibration_date": datetime(2026, 4, 17),
        # NIST traceable, 5% uncertainty
        "initial_activity": ufloat(0.949, 0.05 * 0.949) * 1e-6 * 3.7e10,
        "energies": (
            ufloat(1173.228, 0.0003),
            ufloat(1332.492, 0.0004),
        ),
        "intensities": (
            ufloat(0.9985, 0.00003),
            ufloat(0.999826, 0.0000006),
        ),
        "peak_counts": (23310, 16566),
        "peak_counts_per_second": (194.25, 138.05),
    },
    #    "133Ba": {
    #        "half_life": ufloat(10.536, 0.0008),
    #        "assay_date": datetime(2013, 1, 3),
    #        "calibration_date": datetime.today(),
    #        "initial_activity": 1 * 1e-6 * 3.7e10,
    #        "energies": (
    #            4.29,
    #            30.625,
    #            30.973,
    #            ufloat(80.9979, 0.000011),
    #            ufloat(302.8508, 0.00005),
    #            ufloat(356.0129, 0.00007),
    #        ),
    #        "intensities": (
    #            ufloat(0.157, 0.0008),
    #            ufloat(0.339, 0.0001),
    #            ufloat(0.622, 0.00018),
    #            ufloat(0.329, 0.0003),
    #            ufloat(0.1834, 0.000013),
    #            0.6205,
    #        ),
    #        "peak_counts": (1,1,1,1,1,1),
    #    },
    #    "22Na": {
    #        "half_life": ufloat(2.6019, 0.00005),
    #        "assay_date": datetime(2013, 1, 1),
    #        "calibration_date": datetime.today(),
    #        "initial_activity": ufloat(0.984, 0.05 * 0.984) * 1e-6 * 3.7e10,
    #        "energies": (
    #            511.0,
    #            ufloat(1274.537, 0.0007),
    #        ),
    #        "intensities": (
    #            ufloat(1.7991, 0.000018),
    #            ufloat(0.99940, 0.0000014),
    #        ),
    #        "peak_counts": (1,1),
    #    },
}

# TODO peak detection and background substraction

with open("background.csv") as bg, open("cs137_120s.csv") as cs, open("mystery_120s.csv") as mst:
    background = parse_prospect_csv(bg)[3]
    cesium = parse_prospect_csv(cs)[3]
    mystery = parse_prospect_csv(mst)[3]

# remove the background signal
#mystery["counts"] = mystery["counts"] - background["counts"]
mystery['counts'] = [ mystery_count - background_count for mystery_count, background_count in zip(mystery['counts'], background['counts']) ]
# peaks, _ = scipy.signal.find_peaks(mystery['counts'], 100, 50)
fp = findpeaks(method='topology', limit=80)
#fp2 = findpeaks(method='peakdetect')
#fp2.fit(mystery['counts'])
peakinfo_df = fp.fit(mystery['counts'])['df']
peakinfo_df = peakinfo_df.where(peakinfo_df.peak).dropna()
peak_energies = [mystery['energies'][int(index)] for index in peakinfo_df['x']]
peak_counts = peakinfo_df['y'].values
#peak_counts = peakinfo_df['y'].values.tolist()
print(f"found {len(peak_counts)} peaks:")
for e, c in zip(peak_energies, peak_counts):
    print(e, c, sep=', ')
#breakpoint()
# TODO something shifts the spectrum back to zero
#fp.plot()
#fp2.plot()

#with open("background.json", "w") as bg, open("cs137.json", "w") as cs, open('mystery.json', 'w') as mst:
#    json.dump({'data': background}, bg)
#    json.dump({'data': cesium}, cs)
#    json.dump({'data': mystery, 'peak_energies': peak_energies, 'peak_counts': peak_counts}, mst)


#plt.bar(mystery['energies'], mystery['counts'], width=1)
#plt.vlines(peak_energies, 0, 1000, colors='black', linestyles='dashed', linewidths=0.05)
#plt.savefig('hist.svg')

all_energies = []
all_intensities = []
all_efficiencies = []
for isotope in check_source_properties.keys():
    # A = A₀ exp( ln(2)/t_1/2 * t )
    activity = check_source_properties[isotope]["initial_activity"] * umath.exp(
        -umath.log(2)
        / check_source_properties[isotope]["half_life"]
        * (
            check_source_properties[isotope]["calibration_date"]
            - check_source_properties[isotope]["assay_date"]
        ).days
        / 365
    )
    for energy, intensity, counts_per_second in zip(
        check_source_properties[isotope]["energies"],
        check_source_properties[isotope]["intensities"],
        check_source_properties[isotope]["peak_counts_per_second"],
    ):
        efficiency = (counts_per_second) / intensity / activity
        all_efficiencies.append(efficiency)
        all_energies.append(energy)


# efficiency curve fit model given by equation 11 in
# https://doi.org/10.1016/j.jclepro.2024.143910. we do not apply the natural
# logarithm transform to make it a linear model as it may magnify or diminish
# errors in an unexpected way
# (https://en.wikipedia.org/wiki/Nonlinear_regression#Transformation). scipy's
# curve_fit uses a nonlinear least squares algorithm.
def exp_log_poly(x, A, B, C, D):
    return np.exp(
        A + B * np.log(x) + C * (np.log(x)) ** 2 + D * (np.log(x)) ** 3
    )


popt, _ = scipy.optimize.curve_fit(
    # exp_log_poly,
    lambda x, A, B, C, D: np.exp(
        A + B * np.log(x) + C * (np.log(x)) ** 2 + D * (np.log(x)) ** 3
    ),
    # scale the energies down by 1000 so the curve fit algorithm converges (were in keV, now in eV×10⁻⁶; MeV)
    xdata=np.array(scrub_uncertainties(all_energies)) / 1000,
    ydata=scrub_uncertainties(all_efficiencies),
    p0=(0.9, -1.5, -1.1, -1.3),
    sigma=get_uncertainties(all_efficiencies),
    absolute_sigma=True,
)

print("exp-log-poly fit parameters (A B C D):", popt)

with open("efficiency.json", "w") as file:
    json.dump(
        {
            "energy": scrub_uncertainties(all_energies),
            "efficiency": scrub_uncertainties(all_efficiencies),
            "energy_uncertainty": get_uncertainties(all_energies),
            "efficiency_uncertainty": get_uncertainties(all_efficiencies),
            "exp_log_poly_fit_params": {
                "A": popt[0],
                "B": popt[1],
                "C": popt[2],
                "D": popt[3],
            },
        },
        file,
    )
